# Generated by Django 3.2 on 2022-05-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0004_auto_20220520_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='mae_reportes',
            name='grilla',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='I', max_length=1),
        ),
    ]
