# Generated by Django 3.2 on 2022-05-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0005_mae_reportes_grilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='mae_reportes',
            name='usuario_crea',
            field=models.CharField(default='', max_length=20),
        ),
    ]
