# Generated by Django 3.2 on 2022-05-24 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0006_mae_reportes_usuario_crea'),
    ]

    operations = [
        migrations.AddField(
            model_name='mae_reportes',
            name='fechaRegistro',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
